name: Collect trackers

on:
  schedule:
    - cron: '0 4 * * *'  # 在 UTC 时区的 4 点运行，对应 GMT+8 时区的 12 点
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  merge-data:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set time variable
        run: echo "current_time=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"

      - name: Fetch data
        run: |
          function fetch_url_data() {
            local url="$1"
            local response=$(curl -s "$url")
            # save $response to a var or file
            echo "$response" >> data.txt
          }
          
          fetch_url_data "http://github.itzmx.com/1265578519/OpenTracker/master/tracker.txt" 
          fetch_url_data "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt"
          fetch_url_data "https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt"
          fetch_url_data "https://raw.githubusercontent.com/DeSireFire/animeTrackerList/master/AT_all.txt"
          fetch_url_data "https://t1.hloli.org/tracker.txt"
          
          # 添加从仓库文件下载内容
          response=$(cat ${{ github.workspace }}/single_tracker.txt)
          echo "$response" >> data.txt

      - name: Merge data
        run: |
          cat data.txt | sort -u > bt_tracker.txt
          rm data.txt

      - name: commit
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git add bt_tracker.txt
          git commit -m "${{ env.current_time }} - Merge bt_tracker files"
          git push --force