name: Collect trackers

on:
  schedule:
    - cron: '0 4 * * *'  # 在 UTC 时区的 4 点运行，对应 GMT+8 时区的 12 点
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  merge-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set time variable
        run: echo "current_time=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> "$GITHUB_ENV"

      - name: Fetch data
        run: |
          # 获取时间变量
          time_var="${{ env.current_time }}"
          echo "Current time (GMT+8): $time_var"

      - name: Fetch data
        run: |
          function fetch_url_data() {
            local url="$1"
            local response=$(curl -s "$url")
            # save $response to a var or file
            echo "$response" >> data.txt
          }

          fetch_url_data "https://cdn.jsdelivr.net/gh/XIU2/TrackersListCollection/best.txt"
          fetch_url_data "https://gitee.com/harvey520/www.yaozuopan.top/raw/master/blacklist.txt"
          fetch_url_data "https://t1.hloli.org/tracker.txt"

      - name: Merge data
        run: |
          cat data.txt | sort | uniq > bt_tracker.txt
          rm data.txt

      - name: commit
        run: |
          git config --global user.name 'QiXing1217'
          git config --global user.email 'qihang1217@outlook.com'
          git add bt_tracker.txt
          git commit -m "$time_var - Merge bt_tracker files"
          git push --force